Repository Candidate-College/new-api-weekly-report, pull requests merged in 2024-08, with the labels that each got.

#18 Feat/api versioning
  app/Http/Controllers/UserController.php
  app/Http/Resources/UserResource.php
  composer.lock
  routes/api/v1/api.php
Labels: enhancement

#24 Feat/user login
  .github/workflows/CI.yml
  app/Http/Controllers/AuthController.php
  app/Models/User.php
  bootstrap/app.php
  composer.json
  composer.lock
  config/auth.php
  config/jwt.php
  routes/api/v1/api.php
  tests/Feature/AuthJWTTest.php
Labels: enhancement

#27 Feat/performance feedback
  .github/workflows/CI.yml
  app/Http/Controllers/FeedbackController.php
  app/Http/Controllers/ReportController.php
  app/Http/Controllers/UserController.php
  app/Http/Resources/DailyReportResource.php
  app/Http/Resources/PerformanceFeedbackResource.php
  app/Models/DailyReport.php
  app/Models/User.php
  routes/api/v1/api.php
  tests/Feature/ADatabaseSeederTest.php
Labels: documentation, enhancement, question

#28 Model and migration
  .github/workflows/CI.yml
  app/Models/CLevelDivision.php
  app/Models/Division.php
  app/Models/DivisionKPI.php
  app/Models/OTP.php
  app/Models/User.php
  database/factories/DivisionFactory.php
  database/factories/UserFactory.php
  database/migrations/0001_01_01_000000_create_divisions_table.php
  database/migrations/0001_01_01_000001_create_users_table.php
  database/migrations/0001_01_01_000002_create_cache_table.php
  database/migrations/0001_01_01_000003_create_jobs_table.php
  database/migrations/2024_08_09_142922_create_c_level_divisions_table.php
  database/migrations/2024_08_09_143131_create_kpi_division_table.php
  database/seeders/DatabaseSeeder.php
  database/seeders/DivisionSeeder.php
  database/seeders/UserSeeder.php
  tests/Feature/CLevelDivisionTest.php
Labels: enhancement

#26 Feat/otp
  app/Http/Controllers/AuthController.php
  app/Http/Requests/ResetPasswordRequest.php
  app/Http/Requests/SendOtpRequest.php
  app/Http/Requests/VerifyOtpRequest.php
  app/Mail/SendOtp.php
  app/Models/OTP.php
  app/Repositories/OtpRepository.php
  app/Services/AuthService.php
  app/Services/EmailService.php
  app/Services/OtpService.php
  database/factories/OtpFactory.php
  database/migrations/2024_07_25_085508_create_otps_table.php
  resources/views/mails/otp.blade.php
  routes/api/v1/api.php
  storage/api-docs/api-docs.json
  tests/Feature/OtpRegistrationAndPasswordTest.php
Labels: enhancement

#34 fix: add fillable email verified
  app/Models/User.php
Labels: bug

#37 Enhance OTP email
  app/Mail/SendOtp.php
  app/Services/AuthService.php
  app/Services/EmailService.php
  resources/views/mails/otp.blade.php
  tests/Feature/OtpRegistrationAndPasswordTest.php
Labels: enhancement

#39 feat: Update email configuration for SMTP
  .env.example
  app/Http/Middleware/AllowCLevel.php
  app/Http/Middleware/AllowStaff.php
  app/Http/Middleware/AllowSupervisor.php
  app/Http/Middleware/AllowSupervisorAndStaff.php
  app/Mail/SendOtp.php
  app/Models/CLevelDivision.php
  app/Models/DailyReport.php
  app/Models/Division.php
  app/Models/DivisionKPI.php
  app/Models/KPIRating.php
  app/Models/MonthlyFeedback.php
  app/Models/OTP.php
  app/Models/User.php
  app/Services/AuthService.php
  app/Services/EmailService.php
  app/Services/OtpService.php
  app/Services/UserService.php
  tests/Feature/AuthJWTTest.php
Labels: enhancement

#40 feat: add respond role when login
  app/Http/Controllers/AuthController.php
  routes/api/v1/api.php
  storage/api-docs/api-docs.json
Labels: enhancement

#41 refactor: Modify login method to generate token with role-based authe…
  app/Http/Controllers/AuthController.php
  storage/api-docs/api-docs.json
Labels: enhancement
